### ISSUE TITLE
sshpiper crash with SIGSEGV

### ISSUE THREAD

**Issue by OwOchle** [tg123/sshpiper#468]
When trying to connect to sshpiper (happened in 1.4.x), I get a sigsegv. Here is the stacktrace. Reverting to 1.3.1 fixes the issue
```
panic: runtime error: invalid memory address or nil pointer dereference
piper-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x91c817]
piper-1  |
piper-1  | goroutine 39 [running]:
piper-1  | main.(*daemon).run.func1.2({0xc000029698?, 0x25b?, 0x25b?})
piper-1  |      /home/runner/work/sshpiper/sshpiper/cmd/sshpiperd/daemon.go:270 +0xf7
piper-1  | golang.org/x/crypto/ssh.pipingWithHook({0xb351b0, 0xc00036e1a0}, {0xb351b0, 0xc0000c8b60}, 0xc000308af0)
piper-1  |      /home/runner/work/sshpiper/sshpiper/crypto/ssh/sshpiper.go:385 +0x51
piper-1  | golang.org/x/crypto/ssh.(*PiperConn).WaitWithHook.func3()
piper-1  |      /home/runner/work/sshpiper/sshpiper/crypto/ssh/sshpiper.go:135 +0x45
piper-1  | created by golang.org/x/crypto/ssh.(*PiperConn).WaitWithHook in goroutine 24
piper-1  |      /home/runner/work/sshpiper/sshpiper/crypto/ssh/sshpiper.go:134 +0x173
```

**Comment by tg123** [comment]
fixed #465, i am publishing 1.4.2 with this fix
